# This workflow runs once per day and recreates the Flock master, beta, and
# stable branches with the latest history from Flutter.
#
# The Flock branches are reconstituted by taking the most recent history of
# Flutter's branches, and then replaying all of Flock's changes on top.
# This replay is effectively a rebase, but each change is saved in a patch
# file instead of the git log.

on:
  schedule:
    - cron: '0 12 * * *' # Once per day at noon
  workflow_dispatch: # on button click

# Update these variables to fit your custom fork configuration.
env:
  # Expected GitHub repository variables:
  #
  #  - "FLOCK_REPO": The GitHub location of your Flutter fork.
  #                  WARNING: THIS WORKFLOW WILL DESTROY HISTORY IN THIS REPO!!
  FLOCK_REPO: ${{ vars.FLOCK_REPO }}

  # A Personal Access Token (PAT) so that this action can destroy and create
  # history in the `FLOCK_REPO`.
  GITHUB_PAT: ${{ secrets.REPO_WORKFLOW_PAT }}

name: daily-flock-rebase
permissions:
  contents: write

jobs:
  # This job runs for "master", "beta", and "stable" Flock branches.
  rebase-flock-on-flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        config: [master, beta, stable]

    env:
      FLUTTER_BRANCH: ${{ matrix.config }}

    steps:
      - name: Pre-Flight Checks
        run: |
          echo "Flock Repository: $FLOCK_REPO"
          echo "Flutter branch: $FLUTTER_BRANCH"

      - name: Checkout Nest (this repo)
        uses: actions/checkout@v4
        with:
          path: 'nest'
          fetch-depth: 0 # Checkout everything to get access to the tags
          repository: ${{ github.repository }}
          # TODO: checkout the associated Nest branch
          ref: main
          token: ${{ env.GITHUB_PAT }}

      - name: Checkout Flock
        uses: actions/checkout@v4
        with:
          path: 'nest/flock'
          fetch-depth: 0 # Checkout everything to get access to the tags
          repository: ${{ FLOCK_REPO }}
          ref: ${{ FLUTTER_BRANCH }}
          token: ${{ env.GITHUB_PAT }}

      - name: Fetch Flutter master
        working-directory: nest/flock
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          # Setup upstream to Flutter and fetch the latest from master.
          git remote add upstream https://github.com/flutter/flutter.git
          git fetch upstream $FLUTTER_BRANCH

      - name: Delete Flock branch, recreate, replay Flock
        working-directory: nest/flock
        run: |
          # Checkout a temporary branch so we can manipulate Flock.
          git checkout -b temp

          # Delete Flock branch
          git branch -D $FLUTTER_BRANCH

          # Get fresh version from Flutter.
          git switch -c $FLUTTER_BRANCH upstream/master

          # Switch back to the refreshed master branch.
          git checkout $FLUTTER_BRANCH

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Apply Nest patches to Flock
        run: |
          echo "Apply patches..."
          cd nest
          ./tools/git-import-patches patches

      - name: Force push updated branch to Flock
        working-directory: nest/flock
        run: |
          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "$GITHUB_PAT" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt

          # Replace the previous Flock master branch with our updated branch.
          git push -f origin $FLUTTER_BRANCH
  